"""empty message

Revision ID: 0daa6e5c1731
Revises: 
Create Date: 2019-01-29 21:17:23.549128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0daa6e5c1731'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gradefactor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category1_name', sa.String(length=63), nullable=False),
    sa.Column('category1_weight', sa.Float(), nullable=False),
    sa.Column('category2_name', sa.String(length=63), nullable=True),
    sa.Column('category2_weight', sa.Float(), nullable=True),
    sa.Column('category3_name', sa.String(length=63), nullable=True),
    sa.Column('category3_weight', sa.Float(), nullable=True),
    sa.Column('category4_name', sa.String(length=63), nullable=True),
    sa.Column('category4_weight', sa.Float(), nullable=True),
    sa.Column('category5_name', sa.String(length=63), nullable=True),
    sa.Column('category5_weight', sa.Float(), nullable=True),
    sa.Column('category6_name', sa.String(length=63), nullable=True),
    sa.Column('category6_weight', sa.Float(), nullable=True),
    sa.Column('category7_name', sa.String(length=63), nullable=True),
    sa.Column('category7_weight', sa.Float(), nullable=True),
    sa.Column('category8_name', sa.String(length=63), nullable=True),
    sa.Column('category8_weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('fist_name', sa.String(length=127), nullable=False),
    sa.Column('last_name', sa.String(length=127), nullable=False),
    sa.Column('password_hash', sa.Binary(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('join_code', sa.String(length=127), nullable=False),
    sa.Column('grade_factor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_factor_id'], ['gradefactor.id'], ondelete='restrict'),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_code')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_name', sa.String(length=127), nullable=False),
    sa.Column('assignment_type', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignmentresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ondelete='restrict'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignmentresult')
    op.drop_table('assignment')
    op.drop_table('class')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('gradefactor')
    # ### end Alembic commands ###
