"""empty message

Revision ID: 21190b81b538
Revises: 68100007a6fc
Create Date: 2019-07-23 15:13:06.879817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21190b81b538'
down_revision = '68100007a6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=63), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
