"""empty message

Revision ID: 4a7ec5cca5b0
Revises: be3622cd2130
Create Date: 2019-10-02 20:14:15.069228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a7ec5cca5b0'
down_revision = 'be3622cd2130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gradefactor', sa.Column('points_based', sa.Boolean(), nullable=True))
    op.alter_column('gradefactor', 'category1_weight',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gradefactor', 'category1_weight',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('gradefactor', 'points_based')
    # ### end Alembic commands ###
