"""empty message

Revision ID: 60a6f772dfbe
Revises: a14608a15d51
Create Date: 2019-03-20 20:00:28.145229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a6f772dfbe'
down_revision = 'a14608a15d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gradescale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('a_b', sa.Float(), nullable=False),
    sa.Column('b_c', sa.Float(), nullable=False),
    sa.Column('c_d', sa.Float(), nullable=False),
    sa.Column('d_f', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gradescale')
    # ### end Alembic commands ###
