"""empty message

Revision ID: 7ec0cf0107d6
Revises: 60a6f772dfbe
Create Date: 2019-03-24 21:21:06.464219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec0cf0107d6'
down_revision = '60a6f772dfbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('name', sa.String(length=127), nullable=False))
    op.create_unique_constraint(None, 'class', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class', type_='unique')
    op.drop_column('class', 'name')
    # ### end Alembic commands ###
